name: Build WORD1

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Fix Directory Hierarchy
        run: |
          New-Item -ItemType Junction -Path "$PWD/src/src" -Target "$PWD/src"

      - name: Configure CMake
        run: |
          cmake -S src -B build -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="/wd4013 /wd4091 /wd4101 /wd4201 /wd4716" -DCMAKE_CXX_FLAGS="/wd4013 /wd4091 /wd4101 /wd4201 /wd4716"

      - name: Build WORD1 Executable
        run: |
          cmake --build build --config Release --target WORD1

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Word1-x64
          path: |
            build/bin/Release/WORD1.exe
            build/bin/WORD1.exe
            build/Release/WORD1.exe
            build/**/*.exe
