name: Build WORD1

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        working-directory: src
        run: |
          cmake --preset x64-release -DCMAKE_C_FLAGS="/wd4013 /wd4091 /wd4101 /wd4201" -DCMAKE_CXX_FLAGS="/wd4013 /wd4091 /wd4101 /wd4201"

      - name: Build WORD1 via MSBuild
        run: |
          msbuild out\WORD1.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Word1-x64
          path: |
            out/**/WORD1.exe
            bin/WORD1.exe
            **/*.exe
            !**/CMake*/**
